authors:
  alan:
    name: Alan Tong
    description: Sussy Baka
    avatar: https://avatars.githubusercontent.com/u/4946846
    url: https://github.com/nicejak
  jack:
    name: Jack Mckee
    description: Sussy Baka
    avatar: https://avatars.githubusercontent.com/u/28030861
    url: https://github.com/yack-macker
  zain:
    name: Zain Jabbar
    description: Sussy Baka
    avatar: https://avatars.githubusercontent.com/u/40334752
    url: https://github.com/Zaijab
